import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import Ajv2020 from 'ajv/dist/2020.js';
import addFormats from 'ajv-formats';
import standaloneCode from 'ajv/dist/standalone/index.js';
import { build } from 'esbuild';

type Schema = {
  $id?: string; $ref?: string; $defs?: Record<string, Schema>; const?: unknown;
  enum?: unknown[]; oneOf?: Schema[]; anyOf?: Schema[]; allOf?: Schema[];
  type?: string | string[]; properties?: Record<string, Schema>; required?: string[];
  items?: Schema;
};
const banner = '// Generated by dev/generate-macro-pilot-content-protocol.ts. Do not edit.\n';

/** Generates a CSP-compatible browser validator from the normative registry and helper. */
export async function generateMacroPilotContentProtocol(projectRoot: string) {
  const directory = resolve(projectRoot, 'contracts/macro-pilot/v2');
  const registry = JSON.parse(await readFile(resolve(directory, 'schema-set.json'), 'utf8')) as {
    root: string; resources: { path: string; id: string }[];
  };
  const schemas = await Promise.all(registry.resources.map(async resource => {
    const schema = JSON.parse(await readFile(resolve(directory, resource.path), 'utf8')) as Schema;
    if (schema.$id !== resource.id) throw new Error(`Schema id mismatch: ${resource.path}`);
    return schema;
  }));
  const ajv = new Ajv2020({ strict: false, allErrors: false, messages: false, code: { source: true, esm: true, optimize: 2 } });
  addFormats(ajv);
  for (const schema of schemas) ajv.addSchema(schema);
  const standalone = standaloneCode(ajv, { shape: registry.root });
  const helper = await readFile(resolve(directory, 'validate.mjs'), 'utf8');
  const marker = 'const protectedPath =';
  if (!helper.includes(marker) || !helper.includes("Buffer.byteLength(s, 'utf8')")) {
    throw new Error('Public conformance helper changed; review browser adaptation.');
  }
  const semantics = helper.slice(helper.indexOf(marker)).replace("Buffer.byteLength(s, 'utf8')", 'new TextEncoder().encode(s).byteLength');
  const bundled = await build({
    stdin: { contents: `${standalone}\n${semantics}`, resolveDir: projectRoot, loader: 'js' },
    bundle: true, write: false, format: 'esm', platform: 'browser', target: 'es2022',
    legalComments: 'none', minify: true,
  });
  const root = schemas.find(schema => schema.$id === registry.root)!;
  const name = (key: string) => key === 'message' ? 'ContentTranscriptMessage' : `Content${key.split(/[_.]/).map(part => part[0].toUpperCase() + part.slice(1)).join('')}`;
  const render = (schema: Schema): string => {
    if (schema.$ref) {
      const [resource, fragment] = schema.$ref.split('#/$defs/');
      if (!fragment) throw new Error(`Unsupported type reference: ${schema.$ref}`);
      if (!resource || resource === registry.root) return name(fragment);
      const target = schemas.find(candidate => candidate.$id === new URL(resource, registry.root).href)?.$defs?.[fragment];
      if (!target) throw new Error(`Unknown type reference: ${schema.$ref}`);
      return render(target);
    }
    if ('const' in schema) return JSON.stringify(schema.const);
    if (schema.enum) return schema.enum.map(value => JSON.stringify(value)).join(' | ');
    if (schema.oneOf || schema.anyOf) return `(${(schema.oneOf ?? schema.anyOf)!.map(render).join(' | ')})`;
    if (schema.allOf) return `(${schema.allOf.map(render).join(' & ')})`;
    if (Array.isArray(schema.type)) return schema.type.map(type => render({ ...schema, type })).join(' | ');
    if (schema.type === 'object' && !Object.keys(schema.properties ?? {}).length) return 'Record<string, never>';
    if (schema.type === 'object') return `{ ${Object.entries(schema.properties ?? {}).map(([key, value]) => `${JSON.stringify(key)}${schema.required?.includes(key) ? '' : '?'}: ${render(value)}`).join('; ')} }`;
    if (schema.type === 'array') return `Array<${render(schema.items ?? {})}>`;
    if (schema.type === 'integer' || schema.type === 'number') return 'number';
    if (schema.type === 'string' || schema.type === 'boolean' || schema.type === 'null') return schema.type;
    return 'unknown';
  };
  const definitions = Object.entries(root.$defs!).map(([key, schema]) => {
    const typeName = key === 'request' || key === 'response' ? `${name(key)}Union` : name(key);
    return `export type ${typeName} = ${render(schema)};`;
  }).join('\n');
  const types = `${banner}${definitions}\nexport type ContentOperation = ContentRequestUnion['operation'];\nexport type ContentRequest<O extends ContentOperation = ContentOperation> = Extract<ContentRequestUnion, { operation: O }>;\nexport type ContentResponse<O extends ContentOperation = ContentOperation> = Extract<ContentResponseUnion, { operation: O }>;\nexport type ContentMessage = ${render(root)};\n`;
  return { validators: `${banner}${bundled.outputFiles[0].text}`, types };
}

if (import.meta.main) {
  const projectRoot = resolve(import.meta.dir, '..');
  const generated = await generateMacroPilotContentProtocol(projectRoot);
  await writeFile(resolve(projectRoot, 'src/services/macroPilot/contentValidators.generated.js'), generated.validators);
  await writeFile(resolve(projectRoot, 'src/services/macroPilot/contentTypes.generated.ts'), generated.types);
}
