import type { Tool, MCPServer } from '../types';

// Internal Tools - Only real, functional tools
export const mockInternalTools: Tool[] = [
  // Web Search Tool (uses Tavily/Brave API)
  {
    id: 'web_search',
    name: 'Web Search',
    category: 'web',
    status: 'enabled',
    description: 'Search the web for information with citations',
    icon: 'search',
    config: {
      enabled: true,
      visible: true,
      chatMode: true,
      internal: false,
      provider: 'tavily',
      maxResults: 5,
    },
  },
  // Web fetch tool (direct URL retrieval, no API key required)
  {
    id: 'web_fetch',
    name: 'Web Fetch',
    category: 'web',
    status: 'enabled',
    description: 'Fetch and read a specific URL directly',
    icon: 'globe',
    config: {
      enabled: true,
      visible: true,
      chatMode: true,
      internal: false,
    },
  },
  // File reading tool
  {
    id: 'read_file',
    name: 'Read File',
    category: 'filesystem',
    status: 'enabled',
    description: 'Read file contents from the workspace',
    icon: 'file-text',
    config: {
      enabled: true,
      visible: true,
      chatMode: true,
      internal: false,
    },
  },
  {
    id: 'list',
    name: 'List Files',
    category: 'filesystem',
    status: 'enabled',
    description: 'List files and directories in the workspace',
    icon: 'folder',
    config: {
      enabled: true,
      visible: true,
      chatMode: true,
      internal: false,
    },
  },
  {
    id: 'read',
    name: 'Read Workspace File',
    category: 'filesystem',
    status: 'enabled',
    description: 'Read files directly from the workspace by path',
    icon: 'file-text',
    config: {
      enabled: true,
      visible: true,
      chatMode: true,
      internal: false,
    },
  },
  {
    id: 'write',
    name: 'Write Workspace File',
    category: 'filesystem',
    status: 'enabled',
    description: 'Create or overwrite workspace files',
    icon: 'save',
    config: {
      enabled: true,
      visible: true,
      chatMode: true,
      internal: false,
    },
  },
  {
    id: 'edit',
    name: 'Edit Workspace File',
    category: 'filesystem',
    status: 'enabled',
    description: 'Edit workspace files using exact text replacements',
    icon: 'edit',
    config: {
      enabled: true,
      visible: true,
      chatMode: true,
      internal: false,
    },
  },
  {
    id: 'glob',
    name: 'Glob Files',
    category: 'filesystem',
    status: 'enabled',
    description: 'Find files by glob pattern in the workspace',
    icon: 'search',
    config: {
      enabled: true,
      visible: true,
      chatMode: true,
      internal: false,
    },
  },
  {
    id: 'grep',
    name: 'Grep Workspace',
    category: 'filesystem',
    status: 'enabled',
    description: 'Search file content in the workspace',
    icon: 'search',
    config: {
      enabled: true,
      visible: true,
      chatMode: true,
      internal: false,
    },
  },
  {
    id: 'git_status',
    name: 'Git Status',
    category: 'git',
    status: 'enabled',
    description: 'Get repository status',
    icon: 'git-branch',
    config: {
      enabled: true,
      visible: true,
      chatMode: false,
      internal: false,
    },
  },
  {
    id: 'git_log',
    name: 'Git Log',
    category: 'git',
    status: 'enabled',
    description: 'List repository commits',
    icon: 'history',
    config: {
      enabled: true,
      visible: true,
      chatMode: false,
      internal: false,
    },
  },
  {
    id: 'git_branch_list',
    name: 'Git Branches',
    category: 'git',
    status: 'enabled',
    description: 'List local and remote branches',
    icon: 'git-branch',
    config: {
      enabled: true,
      visible: true,
      chatMode: false,
      internal: false,
    },
  },
  {
    id: 'git_diff',
    name: 'Git Diff',
    category: 'git',
    status: 'enabled',
    description: 'Generate git diff',
    icon: 'split',
    config: {
      enabled: true,
      visible: true,
      chatMode: false,
      internal: false,
    },
  },
  {
    id: 'git_get_tree',
    name: 'Git Tree',
    category: 'git',
    status: 'enabled',
    description: 'Get predicted git tree',
    icon: 'folder-tree',
    config: {
      enabled: true,
      visible: true,
      chatMode: false,
      internal: false,
    },
  },
  {
    id: 'git_add',
    name: 'Git Add',
    category: 'git',
    status: 'enabled',
    description: 'Stage files in git index',
    icon: 'plus',
    config: {
      enabled: true,
      visible: true,
      chatMode: false,
      internal: false,
    },
  },
  {
    id: 'git_commit',
    name: 'Git Commit',
    category: 'git',
    status: 'enabled',
    description: 'Create commit in repository',
    icon: 'check',
    config: {
      enabled: true,
      visible: true,
      chatMode: false,
      internal: false,
    },
  },
  {
    id: 'git_checkout',
    name: 'Git Checkout',
    category: 'git',
    status: 'enabled',
    description: 'Checkout branch or commit',
    icon: 'git-branch',
    config: {
      enabled: true,
      visible: true,
      chatMode: false,
      internal: false,
    },
  },
  {
    id: 'git_reset',
    name: 'Git Reset',
    category: 'git',
    status: 'enabled',
    description: 'Reset repository state',
    icon: 'undo-2',
    config: {
      enabled: true,
      visible: true,
      chatMode: false,
      internal: false,
    },
  },
  {
    id: 'git_stash',
    name: 'Git Stash',
    category: 'git',
    status: 'enabled',
    description: 'Stash local changes',
    icon: 'archive',
    config: {
      enabled: true,
      visible: true,
      chatMode: false,
      internal: false,
    },
  },
  // Internal source citation helper (always enabled, visible in chat toolbox)
  {
    id: 'mark_source_passage',
    name: 'Sources',
    category: 'ai',
    status: 'enabled',
    description: 'Track interesting passages and passages used by the AI',
    icon: 'book-open',
    config: {
      enabled: true,
      visible: true,
      chatMode: true,
      internal: true,
    },
  },
  {
    id: 'read_sources',
    name: 'Read Sources',
    category: 'ai',
    status: 'enabled',
    description: 'Read and filter source passages already saved in this conversation',
    icon: 'book-open',
    config: {
      enabled: true,
      visible: true,
      chatMode: true,
      internal: true,
    },
  },
  {
    id: 'edit_source_passage',
    name: 'Edit Sources',
    category: 'ai',
    status: 'enabled',
    description: 'Update, reclassify, or delete saved source passages',
    icon: 'edit',
    config: {
      enabled: true,
      visible: true,
      chatMode: true,
      internal: true,
    },
  },
  {
    id: 'add_need',
    name: 'Add Need',
    category: 'productivity',
    status: 'enabled',
    description: 'Add a structured need to the project (Architect Mode)',
    icon: 'plus',
    config: {
      enabled: true,
      visible: true,
      chatMode: true,
      internal: true,
    },
  },
  {
    id: 'generate_plan',
    name: 'Generate Plan',
    category: 'productivity',
    status: 'enabled',
    description: 'Generate a project plan from needs (Architect Mode)',
    icon: 'git-merge',
    config: {
      enabled: true,
      visible: true,
      chatMode: true,
      internal: true,
    },
  },
];

// MCP Servers - Empty by default (users can configure their own)
export const mockMCPServers: MCPServer[] = [];

// Default settings
export const defaultToolSettings: Record<string, boolean> = {
  web_search: true,
  web_fetch: true,
  read_file: true,
  list: true,
  read: true,
  write: true,
  edit: true,
  glob: true,
  grep: true,
  git_status: true,
  git_log: true,
  git_branch_list: true,
  git_diff: true,
  git_get_tree: true,
  git_add: true,
  git_commit: true,
  git_checkout: true,
  git_reset: true,
  git_stash: true,
  mark_source_passage: true,
  read_sources: true,
  edit_source_passage: true,
  add_need: true,
  generate_plan: true,
};
export const defaultMCPServerSettings: Record<string, boolean> = {};
